# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rXiBkqtNCkHTL4da1s+t0iahkbx9x16eZcNmLhqjGaDRjeqktf1LDyFK2XZQUAtaT0xoxoAQZCdRI+BiXJ6IPPktcwCH3qpSIWxktPOzQJsPcVxBR0pCOqf8wUqtt4sfOrClETGr0+PL0Pa+eUanK+zLeEyXQITVxzugQUbBacZVgAVoa+HaUgjBWpAAbkcL7RjOYL5oQ+tVVcTWEB+VDkYiEz3F9x3gb5bn+NvuHuuB1BCoQjw56nedYOalL4sANt/gsNql/IwKOAM4+QIMYXu4H6Vb3qXtEHs8Bd+d2gOu4gWYqfAsnRnzkvr8PGN7yxrDtog4Z4ZU8mcyAtk2tJxcXXgKnWlT3yFlEPnIDTfl+59GqFR9DWmB9b1+hGseoe/DUNVLaqOK8M56DAmdZQDIg6U62s0PY0ryiWfdPaofXOrvPov74R7o7VGSgAGOmivByEAL1F0SR7bZ4PZduwLD9ATkmc54YLHIVFkg2AoihTX4EopPJF+6FOugdQThkkrION8Tq/XSLdXBZbOUVlt8gmSDdAvzrYU/DDzeXTLcQD4p79bRHH2awflBQYrsZtMtKOFlVFBeH1NbeYX8dXdJ1iCOPDZMS3yYvLX7fShlZnWAkoZnOS7raX2eH8gZucsOd6XcNvqbdwK+2YT5yqwOYzrVOQneL7IewF2LjuQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
