appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: rXiBkqtNCkHTL4da1s+t0iahkbx9x16eZcNmLhqjGaDRjeqktf1LDyFK2XZQUAtaT0xoxoAQZCdRI+BiXJ6IPPktcwCH3qpSIWxktPOzQJsPcVxBR0pCOqf8wUqtt4sfOrClETGr0+PL0Pa+eUanK+zLeEyXQITVxzugQUbBacZVgAVoa+HaUgjBWpAAbkcL7RjOYL5oQ+tVVcTWEB+VDkYiEz3F9x3gb5bn+NvuHuuB1BCoQjw56nedYOalL4sANt/gsNql/IwKOAM4+QIMYXu4H6Vb3qXtEHs8Bd+d2gOu4gWYqfAsnRnzkvr8PGN7yxrDtog4Z4ZU8mcyAtk2tJxcXXgKnWlT3yFlEPnIDTfl+59GqFR9DWmB9b1+hGseoe/DUNVLaqOK8M56DAmdZQDIg6U62s0PY0ryiWfdPaofXOrvPov74R7o7VGSgAGOmivByEAL1F0SR7bZ4PZduwLD9ATkmc54YLHIVFkg2AoihTX4EopPJF+6FOugdQThkkrION8Tq/XSLdXBZbOUVlt8gmSDdAvzrYU/DDzeXTLcQD4p79bRHH2awflBQYrsZtMtKOFlVFBeH1NbeYX8dXdJ1iCOPDZMS3yYvLX7fShlZnWAkoZnOS7raX2eH8gZucsOd6XcNvqbdwK+2YT5yqwOYzrVOQneL7IewF2LjuQ=}
